version: '3.9'

services:
  db:
    image: postgres:13.10
    env_file: .env
    volumes:
      - pg_data_production:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U $$POSTGRES_USER -d $$POSTGRES_DB"]
      interval: 5s
      timeout: 5s
      retries: 5

  backend:
    image: giny2015/taski_backend
    env_file: .env
    volumes:
      - static:/backend_static/
    depends_on:
      db:
        condition: service_healthy

  frontend:
    image: giny2015/taski_frontend
    env_file: .env
    command: cp -r /app/build/. /frontend_static/
    volumes:
      - static:/static

  gateway:
    image: giny2015/taski_gateway
    env_file: .env
    volumes:
      - static:/staticfiles/
    ports:
      - 8000:80
    depends_on:
      - backend

volumes:
  pg_data_production:
  static:
