services:
  backend:
    image: giny2015/taski_backend
    command: >
      sh -c "
            python manage.py collectstatic --noinput &&
            gunicorn backend.wsgi:application --bind 0.0.0.0:8000"
    volumes:
      - ./backend:/app
      - static_volume:/app/static
      - media_volume:/app/media
    expose:
      - 8000
    env_file:
      - .env
    networks:
      - mynetwork

  gateway:
    image: giny2015/taski_gateway
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./gateway/nginx.conf:/etc/nginx/templates/default.conf.template
      - static_volume:/static
      - media_volume:/media
    depends_on:
      - backend
    networks:
      - mynetwork

volumes:
  static_volume:
  media_volume:

networks:
  mynetwork:
    driver: bridge
